global_proxy: ""

openai_api_base: ""
openai_api_type: ""
openai_api_version: ""
openai_api_rpm: ""
OPENAI_API_MODEL: "gpt-3.5-turbo"
max_tokens_rsp: ""
deployment_id: ""
claude_api_key: ""
serpapi_api_key: ""
serper_api_key: ""
google_api_key: ""
google_cse_id: ""
